# Generated by Django 4.2.7 on 2023-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCO2Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11, verbose_name='Date')),
                ('trend', models.FloatField(max_length=10000, verbose_name='Trend')),
                ('Cycle', models.FloatField(max_length=10000, verbose_name='Cycle')),
            ],
        ),
    ]
