# Generated by Django 4.2.7 on 2023-12-01 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('co2_tracker_app', '0002_alter_globalco2level_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2_tracker_app.transport')),
            ],
        ),
        migrations.CreateModel(
            name='TravelCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2_tracker_app.transport')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2_tracker_app.transporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
