# Generated by Django 4.2.7 on 2023-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_tracker_app', '0003_transport_transporttype_travelco2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelco2',
            options={'verbose_name': 'Travel CO2'},
        ),
        migrations.AddField(
            model_name='travelco2',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
