# Generated by Django 4.2.7 on 2023-12-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co2_tracker_app', '0006_foodco2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCO2',
        ),
    ]
