# Generated by Django 4.2.7 on 2023-12-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('co2_tracker_app', '0008_foodco2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('green_type', models.CharField(blank=True, max_length=200, verbose_name='Green Energy Type')),
                ('amount_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KWH amount')),
                ('co2_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CO2 Kg')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy CO2',
            },
        ),
    ]
