# Generated by Django 4.2.7 on 2023-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_tracker_app', '0009_energyco2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyco2',
            name='green_type',
            field=models.CharField(blank=True, default='---', max_length=200, verbose_name='Green Energy Type'),
        ),
        migrations.AlterField(
            model_name='energyco2',
            name='location',
            field=models.CharField(blank=True, default='---', max_length=200, verbose_name='Location'),
        ),
    ]
