# Generated by Django 4.2.7 on 2023-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co2_tracker_app', '0010_alter_energyco2_green_type_alter_energyco2_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodco2',
            old_name='co2_level',
            new_name='co2_kg',
        ),
        migrations.RenameField(
            model_name='travelco2',
            old_name='co2_level',
            new_name='co2_kg',
        ),
    ]
