# Generated by Django 4.2.7 on 2023-12-14 09:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('co2_tracker_app', '0012_energytype_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodco2',
            name='amount_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Amount, kg'),
        ),
        migrations.AlterField(
            model_name='foodco2',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='foodco2',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
